name: Build GBA ROM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Compile the game
      run: make

    - name: Set Short Hash
      run: |
        SHORT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-7)
        echo "SHORT_HASH=${SHORT_HASH}" >> $GITHUB_ENV

    - name: Upload GBA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GBAmore-${{ env.SHORT_HASH }}
        path: GBAmore.gba
        if-no-files-found: error
