name: Release GBA ROM

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile the game
        run: make clean && make

      - name: Create Release and Upload ROM
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/*.gba
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
